### ISSUE TITLE
The introduction of the program may need to be modified

### ISSUE THREAD

**Issue by mmyyyzpl** [johmedr/pykeos#1]
The introduction of the program may need to be modified
The introduction mentions KS entropy, but there seems to be no relevant content in the program, which can easily mislead readers

**Comment by johmedr** [comment]
Sorry for the late reply. The Sample Entropy, the Approximate Entropy and measures from recurrence quantification analysis can all be used to obtain estimates of the KS entropy (see for instance Faure, Philippe, and Henri Korn. "A new method to estimate the Kolmogorov entropy from recurrence plots: its application to neuronal signals." Physica D: Nonlinear Phenomena 122.1-4 (1998): 265-279.). The relevant code can be found in [entropies.py](https://github.com/johmedr/pykeos/blob/main/pykeos/measures/entropies.py).
